<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>false</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<Configurations>Debug;Release</Configurations>
		<Platforms>x86</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<RootDir>$([System.IO.Path]::GetFullPath('$(SolutionDir)..'))</RootDir>
		<MainProjectBuildDir>$(RootDir)\AgileInspect\bin\$(Configuration)\net8.0-windows\$(RuntimeIdentifier)</MainProjectBuildDir>
		<PluginOutputDir>$(RootDir)\AgileInspect\bin\$(Platforms)\$(Configuration)\net8.0-windows\$(RuntimeIdentifier)\dll\ClipboardMonitorPlugin</PluginOutputDir>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Management" Version="9.0.5" />
		<PackageReference Include="Microsoft.InformationProtection.File" Version="1.15.134" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.61.3" />
		<PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="6.35.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AgileInspect\AgileInspect.csproj" />
	</ItemGroup>

	<Target Name="CopyPluginWithDependencies" AfterTargets="Build">
		<Message Text="PluginOutputDir = $(PluginOutputDir)" Importance="High" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginOutputDir)" SkipUnchangedFiles="true" />

		<ItemGroup>
			<DependencyFiles Include="@(ReferenceCopyLocalPaths)" />
		</ItemGroup>
		<Copy SourceFiles="@(DependencyFiles)" DestinationFolder="$(PluginOutputDir)\libs" SkipUnchangedFiles="true" />

		<ItemGroup>
			<NativeMipFilesX86 Include="$(TargetDir)x86\*.dll" />
			<NativeMipFilesX64 Include="$(TargetDir)x64\*.dll" />
		</ItemGroup>
		<Copy SourceFiles="@(NativeMipFilesX86)" DestinationFolder="$(PluginOutputDir)\libs\x86" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)x86')" />
		<Copy SourceFiles="@(NativeMipFilesX64)" DestinationFolder="$(PluginOutputDir)\libs\x64" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)x64')" />

		<ItemGroup>
			<FilesToDelete Include="$(PluginOutputDir)\libs\*AgileInspect*.dll" />
		</ItemGroup>
		<Delete Files="@(FilesToDelete)" />
	</Target>
</Project>
