<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>false</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath>bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <RootDir>$([System.IO.Path]::GetFullPath('$(SolutionDir)..'))</RootDir>
    <MainProjectBuildDir>$(RootDir)\AgileInspect\bin\$(Configuration)\net8.0-windows\$(RuntimeIdentifier)</MainProjectBuildDir>
    <PluginOutputDir>$(RootDir)\AgileInspect\bin\$(Configuration)\net8.0-windows\$(RuntimeIdentifier)\dll\WatermarkDetectorPlugin</PluginOutputDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Model\best.onnx" />
    <None Remove="Model\windows.onnx" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Model\windows.onnx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
    <PackageReference Include="YoloSharp" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgileInspect\AgileInspect.csproj" />
  </ItemGroup>

  <Target Name="CopyPluginWithDependencies" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginOutputDir)" SkipUnchangedFiles="true" />

    <ItemGroup>
      <DependencyFiles Include="@(ReferenceCopyLocalPaths)" />
    </ItemGroup>
    <Copy SourceFiles="@(DependencyFiles)" DestinationFolder="$(PluginOutputDir)\libs" SkipUnchangedFiles="true" />

    <ItemGroup>
      <FilesToDelete Include="$(PluginOutputDir)\libs\*AgileInspect*.dll" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
  </Target>

</Project>
