<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>false</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
    <OutputPath>bin\Debug\net8.0-windows\win-x64\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
    <OutputPath>bin\Release\net8.0-windows\win-x64\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Model\best.onnx" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Model\best.onnx">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
    <PackageReference Include="YoloSharp" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgileInspect\AgileInspect.csproj" />
  </ItemGroup>

  <Target Name="CopyPluginWithDependencies" AfterTargets="Build">
    <PropertyGroup>
      <PluginRootDir>..\AgileInspect\dll\WatermarkDetectorPlugin</PluginRootDir>
    </PropertyGroup>

    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFolder="$(PluginRootDir)"
      SkipUnchangedFiles="true" />

    <ItemGroup>
      <DependencyFiles Include="@(ReferenceCopyLocalPaths)" />
    </ItemGroup>
    <Copy
      SourceFiles="@(DependencyFiles)"
      DestinationFolder="$(PluginRootDir)\libs"
      SkipUnchangedFiles="true" />

    <ItemGroup>
      <FilesToDelete Include="$(PluginRootDir)\libs\AgileInspect*" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
  </Target>
</Project>
