<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <DebugType>none</DebugType>
    <MainProjectDll>AgileInspect.dll</MainProjectDll>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <!--Plugin list -->
  <ItemGroup>
    <PluginProjects Include="WatermarkDetectorPlugin" />
  </ItemGroup>
  
  <Target Name="BuildPlugins" AfterTargets="Build">
    <MSBuild Projects="@(PluginProjects->'..\\%(Identity)\\%(Identity).csproj')" Targets="Build" />
  </Target>
  
  <!-- Publish plugin -->
  <Target Name="PublishPlugins" AfterTargets="Publish">
    <MSBuild Projects="@(PluginProjects->'..\\%(Identity)\\%(Identity).csproj')" Targets="Publish" Properties="SelfContained=false;PublishSingleFile=false" />
  </Target>

  <Target Name="CopyPluginsAfterPublish" AfterTargets="PublishPlugins">
    <ItemGroup>
      <PluginPublishFiles Include="..\%(PluginProjects.Identity)\bin\$(Configuration)\net8.0-windows\win-x64\publish\win-x64\**\*.dll">
        <PluginName>%(PluginProjects.Identity)</PluginName>
      </PluginPublishFiles>
    </ItemGroup>

    <ItemGroup>
      <MainDllFiles Include="@(PluginPublishFiles)" Condition="'%(Filename)%(Extension)' == '%(PluginName).dll'" />
    </ItemGroup>

    <ItemGroup>
      <DependencyDllFiles Include="@(PluginPublishFiles)" Condition="'%(Filename)%(Extension)' != '%(PluginName).dll'" />
    </ItemGroup>

    <Copy
      SourceFiles="@(MainDllFiles)"
      DestinationFiles="@(MainDllFiles->'$(PublishDir)dll\\%(PluginName)\\%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />

    <Copy
      SourceFiles="@(DependencyDllFiles)"
      DestinationFiles="@(DependencyDllFiles->'$(PublishDir)dll\\%(PluginName)\\libs\\%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>

</Project>