<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>false</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgileInspect\AgileInspect.csproj" />
  </ItemGroup>
</Project>