<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>false</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <MainDll>BrightnessChangePlugin.dll</MainDll>
    <PublishDir>$(MSBuildProjectDirectory)\bin\$(Configuration)\net8.0-windows\win-x64\publish\win-x64\</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgileInspect\AgileInspect.csproj" />
  </ItemGroup>
 
</Project>
